name: Refresh docker NuGet cache

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

  schedule:
    - cron: "0 0,6,12,18 * * *"

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        default: "8.8.x"
        type: choice
        options:
          - "8.8.x"
          - "8.6.x"
      image:
        description: "Image"
        required: true
        default: "ubuntu"
        type: choice
        options:
          - "ubuntu"
          - "centos"

jobs:
  build:
    strategy:
      matrix:
        branch: ["8.8.x", "8.6.x"]
        image: ["ubuntu", "centos"]
      fail-fast: false

    name: "${{ matrix.image }}-${{ matrix.branch }}"
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: "Build dockerfile"
        working-directory: .
        shell: "bash"
        run: |
          docker build --pull --rm -f "dockerfiles/hpcc-prebuild/${{ matrix.image }}.dockerfile" -t vcpkg-${{ matrix.image }}:latest "dockerfiles/hpcc-prebuild" \
          --build-arg BUILD_BRANCH=hpcc-platform-${{ matrix.branch }} \
          --build-arg REPO_OWNER=${{ github.repository_owner }} \
          --build-arg BUILD_TOKEN=${{ secrets.GITHUB_TOKEN }}

      - name: "Refresh cache"
        working-directory: .
        shell: "bash"
        run: |
          docker run --rm vcpkg-${{ matrix.image }}:latest
